baseurl = "http://chaomifan.github.io/"
languageCode = "en-us"
title = "Ethan's PMbook"
theme = "angels-ladder"
disqusShortname = "Ethan's PMbook"

[params]
	subtitle = "信心是黑暗中的灯塔，任何时候都不能丢"
	about = "#"
	weibo = "http://www.baidu.com"
        wechat = "htttp://www.baidu.com"
	jianshu = "http://www.jianshu.com/users/f5820a96231b/timeline"
	github = "http://www.baidu.com"
	mail = "mailto:xielm@qq.com"
	guifan = "/categories/产品规范/"
	fenxi = "/categories/产品分析/"
	jiqiao = "/categories/技巧分析/"
	yanjiu = "/categories/技术研究/"
	demo = “/categories/产品原型/”
	profile = "/images/ethan.png"
	copyright = "Written by Ethan，转载请注明出处，谢谢！"
